[package]
name = "raytracer"
version = "0.1.0"
authors = ["maxkl <max@maxkl.de>"]
edition = "2018"

[dependencies]
cgmath = { version = "0.17.0", features = ["serde"] }
serde = { version = "1.0.114", features = ["derive"] }
typetag = "0.1.5"
dyn-clone = "1.0.2"
rand = "0.7.3"
rand_distr = "0.2.2"
